### ISSUE TITLE
程序本身及安装的建议

### ISSUE THREAD

**Issue by h82815** [GopherTy/v2rayW#2]
非常感谢有这样的项目实现web端的v2ray配置
1、mysql和Redis 相对于这个程序来说还是过于沉重，如果仅用于系统登录和协议配置，那么josn和yaml是更好的选择。
2、service注册指向的路径有点瑕疵，
3、直接clone的项目build.sh无法执行
`alex@nas:~/v2rayW$ ./build.sh s
./build.sh: line 22: statik: command not found
`

**Comment by GopherTy** [comment]
首先非常感谢你的提议。对于以上几点问题做如下解释：
1.对于数据库的使用除了系统登陆，还有用户相关的代理协议管理，用户登陆信息过期后的刷新 token 。这两个数据库使用，目前打算换成更轻量的方式来处理，避免安装其他应用所带来其他不必要的麻烦。
2.注册路径我会进行参考主流的方式进行修改。
3.因为本项目是一个前后端分离项目，所以要把前端包含进来就使用了 statik 第三方库，主要作用是将前端打包好的静态文件嵌入到 go 语言中，后期会对脚本做修改。
最后感谢再次感谢你的建议。

**Comment by GopherTy** [comment]
> 非常感谢有这样的项目实现web端的v2ray配置
> 1、mysql和Redis 相对于这个程序来说还是过于沉重，如果仅用于系统登录和协议配置，那么josn和yaml是更好的选择。
> 2、service注册指向的路径有点瑕疵，
> 3、直接clone的项目build.sh无法执行
> `alex@nas:~/v2rayW$ ./build.sh s ./build.sh: line 22: statik: command not found `

首先非常感谢你的提议。对于以上几点问题做如下解释：
1.对于数据库的使用除了系统登陆，还有用户相关的代理协议管理，用户登陆信息过期后的刷新 token 。这两个数据库使用，目前打算换成更轻量的方式来处理，避免安装其他应用所带来其他不必要的麻烦。
2.注册路径我会进行参考主流的方式进行修改。
3.因为本项目是一个前后端分离项目，所以要把前端包含进来就使用了 statik 第三方库，主要作用是将前端打包好的静态文件嵌入到 go 语言中，后期会对脚本做修改。
最后感谢再次感谢你的建议。
