### ISSUE TITLE
chrome浏览器打不开，目前IE浏览器可以打开页面。

### ISSUE THREAD

**Issue by tableking** [GopherTy/v2rayW#3]

**Comment by GopherTy** [comment]
我这边一直在使用 chrome 浏览器未出现你所说的问题，目前所有浏览器应该都是支持的， 能否贴一下错误提示呢。

**Comment by tableking** [comment]
感谢回复，刚刚发现在没有使用frp内网穿透的情况下也出现了该问题，所以应该不是frp的问题，而是老毛子固件本身的互联网远程访问有什么设置不对或其他问题。浪费你宝贵时间，实在抱歉！谢谢！！
